name: Deploy Site

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'front_end'
      
      - name: Deploy
        uses: actions/deploy-pages@v2
